platform :ios, '14.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Disable boost bawaan RN sebelum instalasi
boost_bawaan = File.join(__dir__, '../node_modules/react-native/third-party-podspecs/boost.podspec')
if File.exist?(boost_bawaan)
  File.rename(boost_bawaan, boost_bawaan + '.disabled')
  puts "🚫 boost bawaan RN dinonaktifkan"
end

target 'NamaProyekTest' do
  config = use_native_modules!

  # Pakai boost lokal
  pod 'boost', :path => './boost_1_83_0'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => FlipperConfiguration.disabled
  )

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
